title: sudodoki's personal blog 
description: >- # this means to ignore newlines until "baseurl:"
  Here be dragons
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sudodoki.name" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sudodoki
github_username:  sudodoki
markdown: rdiscount
plugins:
  - jekyll-feed
disqus:
    shortname: sudodokiname
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
